### ISSUE TITLE
Custom Chars not properly shown

### ISSUE THREAD

**Issue by konig87nikkinakki** [Testato/PCF8574_HD44780_I2C#4]
Good morning,
thank you for library, it's helpful. I ve a small problem, probably it's me not so good in coding.
i created some new chars: one is empty, one is a phone
   uint8_t phone[8] = {0x1f,0x11,0x4,0xe,0x1f,0x15,0x1f}; 
   uint8_t empty[8] = {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0};

before the Setup. Into setup i created the chars

  lcd.createChar(30, phone); delay(50);
  lcd.createChar(31, empty); delay(50);

the sketch is very big and the chars are shown in different Functions, not into setup. but sometime (it's quite random?) it prints phone instead of empty or empty instead of phone. i tried changing HEX array but it still doesnt work.
So i tried to put  lcd.createChar  into the same function where it s used but it still doesnt work, it still swaps the chars sometime.
What can i do? i dont know if it's a library bug, a hardware problem or (probably) my sketch too big.
my used ram is under 50% and i m using Arduino Mega 2560, i2c ports 20 and 21 SDA SCL.
Thank you so much

**Comment by Testato** [comment]
This kind of random problem Is Always a RAM problem or a Logic bug in your schetch.
